version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing node packages
      - npm i
  build:
    commands:
      - echo Build started on `date`
      - npm run build:$ENV
  post_build:
    commands:
      - aws s3 sync build/ s3://shopdesk-react-app-uat