apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    # add an annotation indicating the issuer to use.
    kubernetes.io/ingress.class: "nginx"  
    certmanager.io/issuer: "letsencrypt-prod"
  name: stage-ingress-react-app
  namespace: stage
spec:
  tls: # < placing a host in the TLS config will indicate a cert should be created
  - hosts:
    - uat.shopdesk.co
    secretName: tls-secret-fe # < cert-manager will store the created certificate in this secret.
  rules:
  - host: uat.shopdesk.co
    http:
      paths:
      - backend:
          serviceName: shopdesk-react
          servicePort: 3000
        path: /
